### ISSUE TITLE
realizar refactor automático y manual al crud

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/administrativa_crud_api#106]
con el fin de evitar problemas de respuesta o tiempos de espera excedidos con WSO2 se debe realizar:

- [x] refactor Automatico al api (este se realiza con un script de python)
- [x] desplegar en el 254 el api luego del refactor
   - se debe de tener en cuenta que para que esto sea desplegado el archivo de la ruta `routers/commentsRouter_controllers.go` , no debe de tener los filter que son añadidos al momento de ejecutar el api en algunos casos.
- [x] revisar en el cliente que peticiones están mandando error **502** debido a su demora en la respuesta , listarlos en el presente issue.
- [x] realizar refactor manual a los endpoints listados mediante la tarea del items anterior.

**Comment by anlramirezs11** [comment]
Al realizar el refactor se imprime este mensaje para todos los controladores: 

![Screenshot from 2019-08-06 09-36-46](https://user-images.githubusercontent.com/29903400/62549362-f5e55f80-b82d-11e9-9862-29646abb6c0b.png)

**Comment by anlramirezs11** [comment]
Se queda a la espera del despliegue para relizar pruebas en el cliente.

**Comment by BOTOOM** [comment]
https://autenticacion.udistrital.edu.co/apioas/administrativa_crud_api/v1/vinculacion_docente/get_total_contratos_x_resolucion/11898/TCO|MTO?

esta funcion necesita un refactor ya de devuelve un entero

adicionalmente parece que no esta registrado ese endpoitn en wso2....se enviara correo sobre ello

**Comment by BOTOOM** [comment]
para el refactor de la funcion se sugiere usar el metodo que se usa con el mid 

crear un archivo en modelos con el siguiente [modelo](https://github.com/udistrital/administrativa_mid_api/blob/refactor/models/modelo_refactor.go)

y ysarlo como se usa en las lineas 54 a la 61 del siguiente [archivo](https://github.com/udistrital/administrativa_mid_api/blob/refactor/controllers/gestion_previnculaciones.go)

**Comment by BOTOOM** [comment]
https://autenticacion.udistrital.edu.co/apioas/administrativa_mid_api/v1/gestion_desvinculaciones/consultar_categoria
