### ISSUE TITLE
Creacion api_crud

### ISSUE THREAD

**Issue by Eduargonzalez** [udistrital/administrativa_crud_api#163]
Crear api crud para el sistema de cumplidos teniendo en cuenta los lineamientos suministrados por la OAS
https://github.com/udistrital/lineamientos_oas#generaci%C3%B3n-api-crud

- [x] Dockerizacion
- [x] Refactor

**Comment by diagutierrezro** [comment]
Se realiza el nuevo CRUD del sistema de cumplidos con base en el nuevo modelo de db el cual tiene las siguientes características:

- Se creó el nuevo CRUD con beego según los lineamientos de la OAS.

- Se realiza la dockerizacion del CRUD.

- Finalmente se le hace el refactor según los lineamientos OAS, es importante resaltar que al ejecutar el comando **`goimports -w *.go`** salió error por lo que se realizó el import de las librerias manualmente.

**Comment by ddguerra90** [comment]
El api crud fue desplegado satisfactoriamente en la siguiente ruta http://pruebasapi.intranetoas.udistrital.edu.co:8511/v1/
